# Shared by build.ps1 and test.ps1: the in-box compiler, its references, the product sources and the
# generated version file. Dot-source it.

function Get-FrameworkDir {
    $fw = Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319'
    if (-not (Test-Path $fw)) { $fw = Join-Path $env:WINDIR 'Microsoft.NET\Framework\v4.0.30319' }
    if (-not (Test-Path (Join-Path $fw 'csc.exe'))) { throw "C# compiler not found in $fw" }
    return $fw
}

function Get-CompilerReferences([string]$Framework) {
    # WPF assemblies live in the WPF subfolder; the rest sit in the framework root.
    $need = 'System.dll', 'System.Core.dll', 'System.Xml.dll', 'System.Xaml.dll', 'System.Security.dll',
            'System.Runtime.Serialization.dll', 'WindowsBase.dll', 'PresentationCore.dll', 'PresentationFramework.dll'
    foreach ($dll in $need) {
        $p = Join-Path $Framework $dll
        if (-not (Test-Path $p)) { $p = Join-Path $Framework "WPF\$dll" }
        if (-not (Test-Path $p)) { throw "Missing reference assembly: $dll" }
        "/r:$p"
    }
}

# Everything that ships: the .cs files at the root and in updater\. Tests live in tests\ and never ship.
function Get-ProductSources([string]$Root) {
    $files = @(Get-ChildItem -Path $Root -Filter *.cs -File | Sort-Object Name)
    $updater = Join-Path $Root 'updater'
    if (Test-Path $updater) { $files += @(Get-ChildItem -Path $updater -Filter *.cs -File | Sort-Object Name) }
    $files | ForEach-Object { $_.FullName }
}

# Release versions are MAJOR.MINOR.PATCH, the only form installed updaters offer. A local test build has
# a fourth part (for example 1.2.9.9), so it sorts below the next release and can never be offered as one.
function Test-ClockVersion([string]$Version, [bool]$TestBuild) {
    $pattern = if ($TestBuild) { '^[0-9]{1,4}\.[0-9]{1,4}\.[0-9]{1,5}\.[1-9][0-9]{0,4}$' } else { '^[0-9]{1,4}\.[0-9]{1,4}\.[0-9]{1,5}$' }
    if ($Version -notmatch $pattern) { return $false }
    # Windows version resources hold each part in 16 bits.
    foreach ($part in $Version.Split('.')) { if ([int]$part -gt 65534) { return $false } }
    return $true
}

function Write-VersionFile([string]$Path, [string]$Version) {
    $four = if ($Version.Split('.').Count -eq 3) { "$Version.0" } else { $Version }
    $text = @"
// Generated by build.ps1 or test.ps1 from VERSION. Do not edit.
using System.Reflection;

[assembly: AssemblyTitle("DLB Precision Desktop Clock")]
[assembly: AssemblyProduct("DLB Precision Desktop Clock")]
[assembly: AssemblyCompany("DLB Precision, LLC")]
[assembly: AssemblyCopyright("Copyright (c) 2026 DLB Precision, LLC")]
[assembly: AssemblyVersion("$four")]
[assembly: AssemblyFileVersion("$four")]
[assembly: AssemblyInformationalVersion("$Version")]
"@
    New-Item -ItemType Directory -Force -Path (Split-Path $Path) | Out-Null
    [IO.File]::WriteAllText($Path, $text, (New-Object Text.UTF8Encoding($false)))
}
